import type { Metadata } from 'next';
import 'lenis/dist/lenis.css';
import './globals.css';
import { fragmentGlare, plusJakartaSans } from '@/fonts';
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import { SmoothScroll } from '@/components/providers/SmoothScroll';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { locations, announcedMarkets, extendedCoverage } from '@/content/locations';
import { JsonLd, businessSchema, siteUrl, type ServedArea } from '@/lib/seo';

const SITE_NAME = 'ITP Limo';
const HOME_TITLE = 'ITP Limo | Executive Transportation, Raleigh-Durham & Boston';
const HOME_DESCRIPTION =
  'On-time chauffeur and black car service across Raleigh-Durham, Pinehurst, Wilmington and Boston. Airport transfers with live flight tracking.';

/*
 * Site-wide social defaults: image, site name, locale and card type. Child
 * pages inherit those, which is the point of putting them here.
 *
 * They do NOT inherit a correct og:title. Next does not derive og:title from a
 * page's `title`, so a page setting only `title` ships the homepage's og:title
 * and og:url instead — every inner page shared as the homepage until this was
 * caught. Pages therefore build metadata through `pageMetadata()` in lib/seo,
 * which sets the OG fields explicitly.
 *
 * The image is generated by app/opengraph-image.tsx.
 */
export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: HOME_TITLE,
  description: HOME_DESCRIPTION,
  alternates: { canonical: '/' },
  applicationName: SITE_NAME,
  openGraph: {
    type: 'website',
    siteName: SITE_NAME,
    locale: 'en_US',
    url: '/',
    title: HOME_TITLE,
    description: HOME_DESCRIPTION,
    images: [{
      url: '/og/share.jpg',
      width: 1200,
      height: 630,
      alt: 'ITP Limo — an executive Sprinter beside a Gulfstream on the tarmac',
    }],
  },
  twitter: {
    card: 'summary_large_image',
    title: HOME_TITLE,
    description: HOME_DESCRIPTION,
    images: ['/og/share.jpg'],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, 'max-image-preview': 'large', 'max-snippet': -1 },
  },
};

/*
 * Every market the business covers, page or not, across all three tiers:
 * markets with their own page, markets announced but not yet written, and
 * territory served on request. None of them has premises, so all of them are
 * areaServed on a single business node — which is precisely what areaServed is
 * for on a service-area business.
 */
const servedAreas: ServedArea[] = [
  ...locations.map((l) => ({ name: `${l.city}, ${l.stateAbbr}`, type: 'City' as const })),
  ...announcedMarkets.map((m) => ({ name: `${m.city}, ${m.stateAbbr}`, type: 'City' as const })),
  ...extendedCoverage.map((r) => ({
    name: r.stateAbbr ? `${r.name}, ${r.stateAbbr}` : r.name,
    type: r.type,
  })),
];

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${fragmentGlare.variable} ${plusJakartaSans.variable} scroll-smooth`}
      suppressHydrationWarning
    >
      <body className="bg-[#FAF8F5] text-[#171717] dark:bg-[#0F0F0F] dark:text-[#F8F6F2] font-sans antialiased selection:bg-[#C8B38B] selection:text-[#0F0F0F] overflow-x-hidden transition-colors duration-500">
        <JsonLd data={businessSchema(servedAreas)} />
        <ThemeProvider>
          <SmoothScroll />
          <div className="min-h-screen bg-white dark:bg-[#0F0F0F] text-[#171717] dark:text-[#F8F6F2] font-sans antialiased selection:bg-black selection:text-white dark:selection:bg-white dark:selection:text-black">
            <Navbar />
            <main>{children}</main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
